on:
  schedule:
    - cron: '* 0 * * *'

name: stale

jobs:
  stale:
    if: github.repository == 'kafka-ops/julie'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: 'no-activity'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          exempt-issue-label: 'epic'
          days-before-stale: 30
          days-before-close: 7
